# Generated by Django 3.2 on 2021-04-25 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cellar_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cellar',
            name='show',
            field=models.BooleanField(default=False),
        ),
    ]
