# Generated by Django 3.2 on 2021-04-26 04:51

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product_in_cellar_app', '0002_productincellar_free_quantity'),
        ('product_sale_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductDetail',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.IntegerField(default=0)),
                ('product_in_cellar', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product_in_cellar_app.productincellar')),
                ('product_sale', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product_sale_app.productsale')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
