# Generated by Django 3.2 on 2021-04-25 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_in_cellar_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productincellar',
            name='free_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
