# Generated by Django 3.2 on 2021-04-27 03:05

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('person_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='DEFAULT', max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(default='DEFAULT', max_length=10)),
                ('password', models.TextField()),
                ('password_old', models.TextField()),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='person_app.person')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
