# Generated by Django 3.2 on 2021-04-27 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0002_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(default='CLIENT', max_length=20),
        ),
    ]
